const protectedEditorConfig = {
  generalTitle: "General information",
  generalDescription: "Update your post's general information",
  title: "Editor",
  slug: "Slug",
  generateSlug: "Generate slug",
  description: "Update your post",
  formTitle: "Title",
  formSlug: "Slug",
  categoryTitle: "Category",
  categoryDescription: "Choose a category",
  shortDescriptionTitle: "Short description",
  shortDescriptionDescription: "Update your post's short description",
  mainContentTitle: "Main content",
  mainContentDescription:
    "WYSIWYG Editor with a bubble menu, and drag and drop image upload.",
  formImage: "Image",
  formImageNote: "Only JPG, PNG and GIF files are allowed",
  formImageSize: "File size can't exceed 6MB.",
  coverImageTitle: "Cover Image",
  formCoverImageUploadFile: "Upload a file",
  coverImageDescription: "You can upload one cover image.",
  galleryImageTitle: "Gallery Images",
  galleryImageDescription: "You can upload up to ",
  submit: "Update",
  cancel: "Cancel",
  cofirm: "Confirm",
  placeHolderTitle: "Please provide a title for your blog post",
  placeholderSlug: "Please provide a slug for your blog post",
  placeholderImage: "Image url",
  deleteImage: "Delete image",
  errorMessagesDeleteImage: "Error deleting image",
  errorMessageImageUpload: "Error uploading image",
  successMessagesDeleteImage: "Image deleted",
  successMessageImageUpload: "Image uploaded",
  placeholderDescription:
    "Please provide a short description of your blog post",
  placeholderCategory: "Please choose a category",
  placeholderContent: "Type here your blog post content",
  defaultCategoryId: "4db30a13-2797-4c7d-a0ce-e0c127287a39", // Science
  successMessage: "Your post has been updated",
  errorMessage: "Error updating your post",
  chooseFile: "Upload Files",
  thumbnail: "Thumbnail",
  coverPhoto: "Cover photo",
  uploadDescription: "PNG, JPG, GIF up to 10MB",
  deleteImageQuestion: "Are you sure you want to delete this image?",
  deleteImageDescription: "This action can not be undone.",
};

export default protectedEditorConfig;
