export const bookmarkConfig = {
    title: 'Bookmarks',
    description: 'Manage your bookmarks',
    delete: 'Delete',
    deleted: 'Deleted',
    edit: 'Edit',
    question: 'Are you sure you want to delete this bookmark?',
    warning: 'This action cannot be undone.',
    cancel: 'Cancel',
    confirm: 'Confirm',
    tableHeader: ['Post', 'Date', 'Action'],
    errorDelete: "Couldn't delete this bookmark.",
    successDelete: 'Bookmark deleted.',
    successAdd: 'Bookmark added.',
    errorAdd: "Couldn't add this bookmark.",
    bookmark: 'Bookmark',
    unBookmark: 'Unbookmark',
    bookmarked: 'Bookmarked',
};
