export const buttonConfig = {
  save: "Хадгалах",
  unsave: "Устгах",
  comments: "Сэтгэгдэл",
  views: "Уншсан",
  viewed: "Хандалт",
  thankyou: "Баярлалаа",
  like: "Таалагдлаа",
  doubleLike: "Давхардсан",
  share: "Хуваалцах",
  unlike: "Буцаагдлаа",
  error: "Алдаа гарлаа",
  reverse: "Буцаах",
  back: "Буцах",
  saved: "Хадгалагдлаа",
  deleted: "Устгагдлаа",
};
