export const editorConfig = {
  title: "Editor",
  slug: "Slug",
  generateSlug: "Generate slug",
  description: "Update your post",
  formTitle: "Title",
  formSlug: "Slug",
  formCategory: "Category",
  formDescription: "Description",
  formContent: "Content",
  formImage: "Image",
  submit: "Update",
  cancel: "Cancel",
  placeHolderTitle: "Please provide a title for your blog post",
  placeholderSlug: "Please provide a slug for your blog post",
  placeholderImage: "Image url",
  deleteImage: "Delete image",
  errorMessagesDeleteImage: "Error deleting image",
  errorMessageImageUpload: "Error uploading image",
  successMessagesDeleteImage: "Image deleted",
  successMessageImageUpload: "Image uploaded",
  placeholderDescription:
    "Please provide a short description of your blog post",
  placeholderCategory: "Please choose a category",
  placeholderContent: "Type here your blog post content",
  defaultCategoryId: "4db30a13-2797-4c7d-a0ce-e0c127287a39", // Science
  successMessage: "Your post has been updated",
  errorMessage: "Error updating your post",
  chooseFile: "Choose a file",
  thumbnail: "Thumbnail",
  coverPhoto: "Cover photo",
  uploadDescription: "PNG, JPG, GIF up to 10MB",
};
