export const editorConfig = {
  title: "Editor",
  slug: "Slug",
  generateSlug: "Generate slug",
  description: "Update your post",
  formTitle: "Title",
  formSlug: "Slug",
  formCategory: "Category",
  formDescription: "Description",
  formContent: "Content",
  formImage: "Image",
  formImageNote: "Only JPG, PNG and GIF files are allowed",
  formImageSize: "File size can't exceed 6MB.",
  formCoverImage: "Cover Photo",
  formCoverImageUploadFile: "Upload a file",
  formCoverImageNote: "You can upload only 1 cover photo.",
  formGallery: "Gallery Photos",
  formGalleryNote: "You can upload up to ",
  submit: "Update",
  cancel: "Cancel",
  cofirm: "Confirm",
  placeHolderTitle: "Please provide a title for your blog post",
  placeholderSlug: "Please provide a slug for your blog post",
  placeholderImage: "Image url",
  deleteImage: "Delete image",
  errorMessagesDeleteImage: "Error deleting image",
  errorMessageImageUpload: "Error uploading image",
  successMessagesDeleteImage: "Image deleted",
  successMessageImageUpload: "Image uploaded",
  placeholderDescription:
    "Please provide a short description of your blog post",
  placeholderCategory: "Please choose a category",
  placeholderContent: "Type here your blog post content",
  defaultCategoryId: "4db30a13-2797-4c7d-a0ce-e0c127287a39", // Science
  successMessage: "Your post has been updated",
  errorMessage: "Error updating your post",
  chooseFile: "Upload Files",
  thumbnail: "Thumbnail",
  coverPhoto: "Cover photo",
  uploadDescription: "PNG, JPG, GIF up to 10MB",
  deleteImageQuestion: "Are you sure you want to delete this image?",
  deleteImageDescription: "This action can not be undone.",
};
