export const loginConfig = {
  title: "Нэвтрэх",
  description: "Та өөрт тохирох сонголтоо хийж нэвтэрнэ үү.",
  google: "Google-р нэвтрэх",
  facebook: "Facebook-р нэвтрэх",
  github: "Github-р нэвтрэх",
  email: "Имэйл-р нэвтрэх",
  sendButton: "Нэвтрэх линк илгээх",
  emailRequiredError: "Имэйл хаягаа зөв оруулна уу.",
  new: "Шинэ",
  posts: "Бичсэн",
  saved: "Хадгалсан",
  logOut: "Гарах",
  settings: "Тохиргоо",
  or: "Эсвэл",
  emailSent: "Нэвтрэх линкийг имэйлээр илгээсэн.",
  error: "Алдаа гарлаа.",
  close: "Хаах",
};
