export const postConfig = {
    title: 'Posts',
    description: 'Manage your posts',
    delete: 'Delete',
    edit: 'Edit',
    update: 'Update',
    questionDelete: 'Are you sure you want to delete this post?',
    warning: 'This action cannot be undone.',
    cancel: 'Cancel',
    confirm: 'Confirm',
    tableHeader: ['Post', 'Date', 'Action'],
    updatePost: 'Update post',
    newPost: 'Create new post',
    successDelete: 'Post deleted.',
    successAdd: 'Post added.',
    successUpdate: 'Post updated.',
    errorAdd: "Couldn't add this post.",
    errorDelete: "Couldn't delete post.",
    errorUpdate: "Couldn't update post.",
    author: 'Author',
};
